### ISSUE TITLE
Hangar, or galaxy gates

### ISSUE THREAD

**Issue by bogdan-dudu** [kaiserdj/Darkorbit-client#10]
returns couldn't load plugin.  Game also not starting, same message.

Ubuntu 20.04 .

**Comment by kaiserdj** [comment]
Do you have the latest version of the client?

**Comment by celikfatih** [comment]
My solution here may work for you #11

**Comment by kaiserdj** [comment]
This problem should be fixed with the last commit, I close the issue.

If you have problems again, please reopen the issue
