### ISSUE TITLE
Url blocking by Facebook

### ISSUE THREAD

**Issue by ToastcodeDev** [kaiserdj/Darkorbit-client#12]
`The URL "Body of an error/warning message. Title is: This URL Is Blocked" has been blocked from Facebook. ` That is the error that comes up, it also says something like you must register the url of the application in facebook to be able to identify it as safe.

**Comment by kaiserdj** [comment]
That is an internal darkorbit problem, if you try to log in from Facebook with a normal browser or with the original darkorbit client. The same error comes out.

I can't do anything to fix it

**Comment by ToastcodeDev** [comment]
I assumed it as soon as I saw that it also happened in the browser, I am going to ask the discord staff about this error so that they resolve this api error.
