### ISSUE TITLE
NPM error when starting on Ubuntu

### ISSUE THREAD

**Issue by timslo** [kaiserdj/Darkorbit-client#13]
Software:
Linux Ubuntu 20.04.2 LTS
Node version v10.19.0
NPM version 6.14.4

I did all your steps, but when I run "npm start", I get this error:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle darkorbit-client@2.1.2~prestart: darkorbit-client@2.1.2
6 info lifecycle darkorbit-client@2.1.2~start: darkorbit-client@2.1.2
7 verbose lifecycle darkorbit-client@2.1.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle darkorbit-client@2.1.2~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Darkorbit-client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle darkorbit-client@2.1.2~start: CWD: /home/user/Darkorbit-client
10 silly lifecycle darkorbit-client@2.1.2~start: Args: [ '-c', 'electron .' ]
11 info lifecycle darkorbit-client@2.1.2~start: Failed to exec start script
12 verbose stack Error: darkorbit-client@2.1.2 start: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid darkorbit-client@2.1.2
14 verbose cwd /home/user/Darkorbit-client
15 verbose Linux 5.8.0-44-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v10.19.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error darkorbit-client@2.1.2 start: `electron .`
23 error spawn ENOENT
24 error Failed at the darkorbit-client@2.1.2 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by kaiserdj** [comment]
If you haven't modified anything, it should work. 
I just tried it for good measure, with an ubuntu vanilla. 

Example:

Latest version of the Darkorbit client
Ubuntu: 20.04.2 LTS
node: 12.19.0
npm: 6.14.8

![image](https://user-images.githubusercontent.com/5487950/110255979-b39a7c00-7f96-11eb-996b-5af6cf63af65.png)
