### ISSUE TITLE
Can't use 3D mode

### ISSUE THREAD

**Issue by Andrzejone** [kaiserdj/Darkorbit-client#19]
When Using your client I can't manage it to work in 3D mode, when on normal browser it's working with no problems.
![image](https://user-images.githubusercontent.com/39127677/111554150-0e498a00-8786-11eb-9d8a-7e21e4d444b5.png)

![image](https://user-images.githubusercontent.com/39127677/111554197-26b9a480-8786-11eb-9b9c-ca5726bcce58.png)

**Comment by ToastcodeDev** [comment]
Try reinstalling the launcher, although it is better to wait for an official response from the creator because it may be a bad configuration in your **Flash Player** plugin.

**Comment by kaiserdj** [comment]
It is strange, I have never seen that 3d cannot be activated. Can you use it in the official client?

**Comment by Andrzejone** [comment]
Yes. On Official client it's working. 
I tried reinstalling your client, clearing cache IE, didn't tried flash reinstall only

**Comment by kaiserdj** [comment]
mmmm, What a curious bug, try deleting the launcher and deleting the darkorbit-client folders found in appdata / roaming, and then install the latest version, normally

**Comment by Andrzejone** [comment]
![image](https://user-images.githubusercontent.com/39127677/111649524-bdc54180-8804-11eb-83c0-7e5f2b22f09a.png)

Uninstalled your client. Deleted all files found, installed official darkorbit client, 3D works good.
Uninstalled official client, deleted all foun files, installed your client, 3D not work.

**Comment by ToastcodeDev** [comment]
> mmmm, What a curious bug, try deleting the launcher and deleting the darkorbit-client folders found in appdata / roaming, and then install the latest version, normally

I would say that it is quite strange since from what I see in the launcher settings it uses certain characteristics of the original.

**Comment by Andrzejone** [comment]
I'm in impass
idk what try

**Comment by kaiserdj** [comment]
have you tried with another account or use the client on another pc?

**Comment by Andrzejone** [comment]
tried with another acc. Don't have another pc, just junk laptop when it's working like it should

**Comment by fabio1999ita** [comment]
i got problem too

**Comment by fabio1999ita** [comment]
![video](https://user-images.githubusercontent.com/27001568/115167220-00559480-a0b7-11eb-8b1e-9ad7b4713db0.gif)
@kaiserdj @kaiserdj make this in loading for fix problem

**Comment by Andrzejone** [comment]
Don't work for me

**Comment by kaiserdj** [comment]
This bug is very rare since it is difficult for me to find the problem because it does not happen to me.

Does the original darkorbit launcher work well for you?

**Comment by Andrzejone** [comment]
yes. That's why it's strange.
Hm. I have installed since new year old version of Flash, for playing in normal browser.
Right now I have installed Adobe Flash Player NPAPI 32.0.0.465 and PPAPI 32.0.0.344.
I updated today you client, but nothing changed.

**Comment by kaiserdj** [comment]
Open the client as a developer, you have to open a cmd and go to the executable.exe folder of the launcher and add the parameter -d

Then send me all the text that comes out in the cmd

Instructions:
https://user-images.githubusercontent.com/5487950/119912824-7a9df200-bf5c-11eb-86b0-787ce0ce277e.mp4

**Comment by Andrzejone** [comment]
![image](https://user-images.githubusercontent.com/39127677/119913501-5e9b5000-bf5e-11eb-82ca-61ac70d6d190.png)

**Comment by Andrzejone** [comment]
![image](https://user-images.githubusercontent.com/39127677/119913542-6fe45c80-bf5e-11eb-9d87-a41613849c76.png)
Got This

**Comment by kaiserdj** [comment]
No error appears on the console ...

Is your user an administrator on the pc?

**Comment by Andrzejone** [comment]
yeep.
Only user on whole pc

**Comment by fabio1999ita** [comment]
maybe his pc or system is corrupt

**Comment by Andrzejone** [comment]
my  pc don't have case. Parts are lying on shelf.
Can be corrupted :D

**Comment by kaiserdj** [comment]
Do you have any other pc to try?

**Comment by Andrzejone** [comment]
only laptop. It's working good on him.

**Comment by Andrzejone** [comment]
For now, on this pc I'm using vertex browser. Friend sended me. 3d is working good on it too

**Comment by kaiserdj** [comment]
Still giving problems with the latest version?

**Comment by ODAKAB** [comment]
can you try playing with app-specific settings on nvidia control panel, if you are a nvidia gpu user

**Comment by Andrzejone** [comment]
AMD RADEON HD5550. Very old gpu. Non special setings made. I will try something on my own later and gib feedback

**Comment by kaiserdj** [comment]
Install this modified version of the launcher https://gofile.io/d/9ISgdl

What it does is that when starting the client as a developer, it prints the cmd the GPU Information and enters a flash player test page.

Please follow the steps I gave you in this comment(https://github.com/kaiserdj/Darkorbit-client/issues/19#issuecomment-850029274) again and send me another screenshot of what you get in the cmd.

Thanks and sorry for the problems

**Comment by Andrzejone** [comment]
I'm opening Powershell as on vid, but none of this info is show, only the previous one. It's asking for update, I'm denying it and doing steps from your post.
I opened installer as Admin having install localization opened to see if it's installing there for sure.

![image](https://user-images.githubusercontent.com/39127677/121908923-b9d68c00-cd2d-11eb-878e-9e659de2363b.png)

**Comment by kaiserdj** [comment]
I'm really sorry, it was my fault and I uploaded the normal version instead of the modified version for testing ...

Here is the correct version to test: https://gofile.io/d/1k7bvs

**Comment by kaiserdj** [comment]
I'm really sorry, it was my fault and I uploaded the normal version instead of the modified version for testing ...

Here is the correct version to test: https://mega.nz/file/aNpHRSDB#rKufI5JhTw4K57gXkoARp5J5YRtITAa98suJS4Jen_g

**Comment by Andrzejone** [comment]
Don't worry. Thank's for help.
![image](https://user-images.githubusercontent.com/39127677/122139410-3b6f0c80-ce49-11eb-9334-45ff11a7b367.png)

**Comment by kaiserdj** [comment]
There you can see the problem, I do not know the reason but I do not suppose that it will be something about drivers or their configuration.

Try to install the latest version of the drivers available for your graphics and try to activate all the options for the hardware acceleration to work.

I think it is not the client's problem if not your pc. Try to output something like this on the Data GPU:
```
Data GPU:
{
  '2d_canvas': 'enabled',
  gpu_compositing: 'enabled',
  multiple_raster_threads: 'enabled_on',
  oop_rasterization: 'enabled',
  opengl: 'enabled_on',
  protected_video_decode: 'unavailable_off',
  rasterization: 'enabled',
  skia_renderer: 'enabled_on',
  video_decode: 'enabled',
  vulkan: 'disabled_off',
  webgl: 'enabled',
  webgl2: 'enabled'
}
```

**Comment by kaiserdj** [comment]
@Andrzejone Did you fix it?

**Comment by Andrzejone** [comment]
nope. I'm nearly using computeer 24/24 so, gonna try in couple of hours when project will be done and gib feedback.

**Comment by kaiserdj** [comment]
I close the issue, if you keep having trouble or anything. Write here again, or create a new one or speak for discord

**Comment by Andrzejone** [comment]
I resolved the issue by installing unofficial graphic drivers from amernimezone.
Old Radeon HD 5550
