### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by ErikAlejandroGomez** [kaiserdj/Darkorbit-client#27]
I get stuck in "loa" of the word loading in the calendar ¿Can u help me?

**Comment by ErikAlejandroGomez** [comment]
![Uploading Captura de Pantalla 2021-05-27 a la(s) 22.24.15.png…]()

**Comment by ErikAlejandroGomez** [comment]
https://user-images.githubusercontent.com/62352658/119929848-8cbb6880-bf3b-11eb-81cb-0f0eeb2921c7.mp4

**Comment by maksimka5367** [comment]
Clearing the cache in the new version doesn't help, but I tried creating a new user with administrator rights. It helped, everything is loading. Try. Mac os

**Comment by ErikAlejandroGomez** [comment]
It is what I did, clear the cache from these commands ~/Library/Caches
 /Library/Caches in the Finder . but I do not know if you refer to the client's cache that I have no idea how to delete it

**Comment by ErikAlejandroGomez** [comment]
Create a new user with administrator rights where?

**Comment by ErikAlejandroGomez** [comment]
I have cleared the cache directly from the client but it still gets stuck in loading :(
https://user-images.githubusercontent.com/62352658/119931685-0ef95c00-bf3f-11eb-9e70-f5dd531db56f.mp4

**Comment by maksimka5367** [comment]
https://osxdaily.com/2017/07/17/how-create-new-admin-account-mac/
Download the client in this user. Tell me if it worked or not

**Comment by ErikAlejandroGomez** [comment]
ok, once the administrator user is installed, what do I do?

**Comment by maksimka5367** [comment]
In this new user, just download the game client.

**Comment by ErikAlejandroGomez** [comment]
works!  Thank you so much.  but :( every time I want to play, will I have to change user?

**Comment by maksimka5367** [comment]
Unfortunately, yes.

**Comment by ErikAlejandroGomez** [comment]
well, thank u so much

**Comment by kaiserdj** [comment]
Many thanks to @maksimka5367 for helping @ErikAlejandroGomez, I will investigate if I can fix the problems for non-admin users.

I close this issue for the moment, anything can be opened without problem

**Comment by Whiskas228** [comment]
Same problem on linux

**Comment by kaiserdj** [comment]
Do you still have the same problem with the latest version and clearing the cache?

**Comment by Whiskas228** [comment]
> Do you still have the same problem with the latest version and clearing the cache?

On version 2.2.0 and 2.2.1 (i didn't check other versions) client isn't working and clearing the cache doesn't help

**Comment by kaiserdj** [comment]
To manually clear all launcher data, delete the following folder:
Win: C:\Users{USERNAME}\AppData\Roaming\darkorbit-client
Mac: ~/Library/Application Support/darkorbit-client
Linux: ~/.config/darkorbit-client
Close the launcher completely and delete the folder indicated above, if it continues to give problems let me know

**Comment by Whiskas228** [comment]
> To manually clear all launcher data, delete the following folder:
> Win: C:\Users{USERNAME}\AppData\Roaming\darkorbit-client
> Mac: ~/Library/Application Support/darkorbit-client
> Linux: ~/.config/darkorbit-client
> Close the launcher completely and delete the folder indicated above, if it continues to give problems let me know

Thanks, now button of start is working

**Comment by ErikAlejandroGomez** [comment]
Sorry, I didn't rebice my inbox. Sorry but that route does not lead me anywhere on mac os
________________________________
De: Kaiserdj ***@***.***>
Enviado: sábado, 29 de mayo de 2021 08:29 a. m.
Para: kaiserdj/Darkorbit-client ***@***.***>
CC: ErikAlejandroGomez ***@***.***>; Mention ***@***.***>
Asunto: Re: [kaiserdj/Darkorbit-client] Failed to start (#27)


To manually clear all launcher data, delete the following folder:
Win: C:\Users{USERNAME}\AppData\Roaming\darkorbit-client
Mac: ~/Library/Application Support/darkorbit-client
Linux: ~/.config/darkorbit-client
Close the launcher completely and delete the folder indicated above, if it continues to give problems let me know

**Comment by kaiserdj** [comment]
This video may help you find the folder
https://user-images.githubusercontent.com/5487950/120343511-13d05e00-c2f9-11eb-879e-db6b69986ce6.mp4

If you want you can enter the official discord of the project to give you a faster help: https://discord.gg/vHqAaxS7xF

**Comment by ErikAlejandroGomez** [comment]
It works, thank you so much, you really are my hero


El 1 jun 2021, a las 8:49, Kaiserdj ***@***.******@***.***>> escribió:



This video may help you find the folder
https://user-images.githubusercontent.com/5487950/120343511-13d05e00-c2f9-11eb-879e-db6b69986ce6.mp4

If you want you can enter the official discord of the project to give you a faster help: https://discord.gg/vHqAaxS7xF
