### ISSUE TITLE
Couldn't load plugin

### ISSUE THREAD

**Issue by dmgcsilva** [kaiserdj/Darkorbit-client#3]
Hey, when I try to access the hangar or the actual game the only thing shown is a message saying : "Couldn't load plugin"

I'm on linux Kubuntu.
Thanks

**Comment by kaiserdj** [comment]
I'm trying to fix that problem, sorry for the problems

If you want to play from linux you can use chromium, see this guide: https://github.com/kaiserdj/Darkorbit-client/wiki/Load-darkoribit-on-linux-with-chromium

**Comment by kaiserdj** [comment]
Fixed up
