### ISSUE TITLE
Venom Ship Issue

### ISSUE THREAD

**Issue by vitmitul** [kaiserdj/Darkorbit-client#30]
![image](https://user-images.githubusercontent.com/21157921/121405385-815d3980-c94c-11eb-9eca-f4fa187ec5ef.png)

I get this error after update.

**Comment by kaiserdj** [comment]
I think that's a darkorbit bug, unless you used darkdev to modify the requests ![kekw](https://cdn.frankerfacez.com/emoticon/381875/1)

**Comment by vitmitul** [comment]
didnt modify anything, will try to reinstall

**Comment by ODAKAB** [comment]
darkorbit related, you can close
