### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by mscoder4434** [kaiserdj/Darkorbit-client#33]
![image](https://user-images.githubusercontent.com/56936047/123880374-2e731280-d94b-11eb-9aa0-291a5585c98d.png)
--
![hata2](https://user-images.githubusercontent.com/56936047/123879142-19957f80-d949-11eb-93d9-6aa53f858c95.jpg)

**Comment by mscoder4434** [comment]
![image](https://user-images.githubusercontent.com/56936047/123879435-945e9a80-d949-11eb-95cb-189087df15e4.png)
![image](https://user-images.githubusercontent.com/56936047/123879478-a5a7a700-d949-11eb-9968-3ec3bef3e0f6.png)

**Comment by mscoder4434** [comment]
flash stopped working after build

**Comment by kaiserdj** [comment]
build electron-tutorial-app-win32-ia32?
That is not in this project

**Comment by mscoder4434** [comment]
![image](https://user-images.githubusercontent.com/56936047/124359448-b9932780-dc2d-11eb-9347-f138ff25a5b9.png)

**Comment by mscoder4434** [comment]
how is build code ?

**Comment by mscoder4434** [comment]
https://user-images.githubusercontent.com/56936047/124359704-c2382d80-dc2e-11eb-944f-f2ca4d88f3cc.mp4

**Comment by kaiserdj** [comment]
> how is build code ?

Run: npm run test-build

I have pending to change the name of the scripts

**Comment by mscoder4434** [comment]
https://user-images.githubusercontent.com/56936047/124364590-2e288f00-dc4b-11eb-9265-d693ccfbbf48.mp4

**Comment by kaiserdj** [comment]
Delete the whole project and clone the project again with git, then install the libraries with: npm i
and try again

I have the 14.17.1 version of node and I have no problem

**Comment by mscoder4434** [comment]
can you compress it and send it to me

**Comment by mscoder4434** [comment]
https://user-images.githubusercontent.com/56936047/124365574-aeea8980-dc51-11eb-9613-296c94800c2b.mp4

the problem continues

**Comment by kaiserdj** [comment]
https://github.com/electron-userland/electron-builder/issues/5668

**Comment by kaiserdj** [comment]
> can you compress it and send it to me

All modifications are uploaded to github.


With the following versions and the current project main, it should work without problems:
-Node.js: v14.17.1
-Npm: v6.14.13
