### ISSUE TITLE
XMLDOM ISSUE

### ISSUE THREAD

**Issue by SirErox** [kaiserdj/Darkorbit-client#38]
i just trying to install the launcher on debian dist, but i cant run for this: _Misinterpretation of malicioues XML input_, i tried to manually upgrade the file, but it doesnt work, what i need to do? (note: i followed the instruccions and this happened)

**Comment by SirErox** [comment]
btw, the xmldom is the problem... that file

**Comment by kaiserdj** [comment]
Buenas tardes,
Sorry for your problem first, but I need more information (screenshot, console log, error message, etc).

Do you have the latest version of the project downloaded?

The error seems very strange to me, since xmldom has not been used for many versions

All the best

**Comment by kaiserdj** [comment]
I close the issue, due to lack of reply.
If you want to say anything, feel free to reopen the issue
