### ISSUE TITLE
Doesn't show page until it fully loads

### ISSUE THREAD

**Issue by ODAKAB** [kaiserdj/Darkorbit-client#4]
Simply click on a different category on DO Backpage and you will notice it's trying to load whole page in background before showing it to us. I think this wasn't an intended behaviour and feels like our click isn't registered if we don't get an instant response from browser.

**Comment by kaiserdj** [comment]
I'm not sure I understand what you mean, sorry

**Comment by ODAKAB** [comment]
![x](https://user-images.githubusercontent.com/49538323/106984266-4964a080-6778-11eb-8b1c-1cd0f5b18645.png)

**Comment by kaiserdj** [comment]
Maybe I incorporate this: https://ricostacruz.com/nprogress/

**Comment by ODAKAB** [comment]
That looks amazing but i have no experience if you meant to ask help :(

**Comment by cipscorbasi** [comment]
I think ODAKAB is talking about, when you go to a page like Clans or Hangar, launcher waits for the whole page to be loaded in cache to display. But when on browser the page switches immediately to chosen page and loading the contents after that. Could be useful when server or ur internet is laggy.

**Comment by kaiserdj** [comment]
https://user-images.githubusercontent.com/5487950/107593639-19058200-6c10-11eb-90e1-c7dd75ddf8b9.mp4

This is what you wanted, right?

**Comment by ODAKAB** [comment]
Seems like loading bar appears after page loads and it won't let us know our click is registered. We should see it immediately while a page is loading.

**Comment by kaiserdj** [comment]
Yep fix that this morning 2142f2ba09fca451bacaafcd8817fed5b6cc49be

**Comment by kaiserdj** [comment]
Before the page is downloaded, the loading bar appears

**Comment by kaiserdj** [comment]
Example: 

https://user-images.githubusercontent.com/5487950/107662948-198f2e80-6c8b-11eb-9968-93746feaa371.mp4
