### ISSUE TITLE
Darkorbit client not work

### ISSUE THREAD

**Issue by kashifhamee** [kaiserdj/Darkorbit-client#43]
darkorbit client not work plz fix this i m use your client but 3 or 4 days he not work
i m like your work for this client thank you make this client open but its blank not show anything plz plz fix this issue i m attach screen shot

![Untitled](https://user-images.githubusercontent.com/91802194/135730073-05fe20f8-9298-40b1-843a-04b7458035a6.png)

**Comment by kaiserdj** [comment]
This is a known bug, if as soon as the client opens the window is blank, move the window a little and the image will appear.

I am working on fixing it

**Comment by kashifhamee** [comment]
thank you brother you reply me plz plz fix this bug i m use your client for 8 months but this bug show 5 days ago

**Comment by kaiserdj** [comment]
Try clearing the client's cache, that may fix it
![image](https://user-images.githubusercontent.com/5487950/135751627-246153c3-000d-41df-9986-ab4953f18cb5.png)

**Comment by kashifhamee** [comment]
Brother i m try this clear cache many time he not work i m use your client 1.0.6 or 2.1.1 or 2.1.2 or 2.2.0 or 2.5.1 same issue plz plz plz fix this plz plz  brother

**Comment by kaiserdj** [comment]
It is a strange bug since you are the only one who has told me about this error, looking for a little information try to do the following things:
- Update Windows to Windows 7 SP1
- Install .NET Framework 4.8
- Delete the d3dcompiler_47.dll file from the build directory (see issue here: https://github.com/electron/electron/issues/7049#issuecomment-369365328)
- Uninstall the launcher and delete all data from it (appdata/darkorbit folder)

**Comment by klyxmaster** [comment]
HI..
Just to let you know, I have the same white screen issue, I usually log on from the cmd prompt. Not a huge deal, not sure if it is the server doing it, or the source.. I dont' seem to get any errors.
Did notice that you have to put the parameters in a certain order, or it wont load.
example you have to use it --api xxx --url and it works... but switch it around it wont load.
anyways I'll keep watch on the white screen issue.
thanks for the work you do...

**Comment by kaiserdj** [comment]
I close the issue, due to lack of reply.
If you want to say anything, feel free to reopen the issue
