### ISSUE TITLE
PepperFlashPlayer architecture (have 'i386,x86_64', need 'arm64e'))

### ISSUE THREAD

**Issue by markusmarecki** [kaiserdj/Darkorbit-client#48]
021-11-02 21:11:06.290 Electron Helper (Plugin)[8141:75799] Error loading /Users/xxxxx/dark/Darkorbit-client/flash/PepperFlashPlayer.plugin/Contents/MacOS/PepperFlashPlayer:  dlopen(/Users/xxxxx/dark/Darkorbit-client/flash/PepperFlashPlayer.plugin/Contents/MacOS/PepperFlashPlayer, 0x0106): tried: '/Users/xxxxx/dark/Darkorbit-client/flash/PepperFlashPlayer.plugin/Contents/MacOS/PepperFlashPlayer' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/local/lib/PepperFlashPlayer' (file system sandbox blocked open()), '/usr/lib/PepperFlashPlayer' (no such file)
brew install pepper-flash

**Comment by kaiserdj** [comment]
Could you give me more information about what equipment and operating system the client is running?

**Comment by kaiserdj** [comment]
If you have problems again or you can provide more information, reopen the issue or open a new one, whichever is more comfortable for you.

All the best

**Comment by alexperez52** [comment]
This is most likely related to [#58 ](https://github.com/kaiserdj/Darkorbit-client/issues/58)
I got a similar error on the default OS on the M1 Macbook Pro.
