### ISSUE TITLE
using it as a 32-bit

### ISSUE THREAD

**Issue by mscoder4434** [kaiserdj/Darkorbit-client#50]
With this source code, it is only suitable for 64-bit systems. on a 32-bit system, this client does not open.

**Comment by mscoder4434** [comment]
![image](https://user-images.githubusercontent.com/56936047/147372695-b7648809-8710-40fd-8919-79fee27a9344.png)

**Comment by kaiserdj** [comment]
Could you give me more information about what equipment and operating system the client is running?

**Comment by kaiserdj** [comment]
If you have problems again or you can provide more information, reopen the issue or open a new one, whichever is more comfortable for you.

All the best
