### ISSUE TITLE
Opening a pilot profile

### ISSUE THREAD

**Issue by Plateria** [kaiserdj/Darkorbit-client#51]
When you open the pilot profile of yourself or another player, where you can see his rang and play hours etc. there is no possibility to go back. This means that you have to close the whole client and reopen it. Maybe opening the pilot profile in another window is an option.

**Comment by kaiserdj** [comment]
Thanks for saying it, it is added to the list of improvements to make

**Comment by kaiserdj** [comment]
This improvement will be introduced in the next version of the client, thank you very much and greetings.
