### ISSUE TITLE
Issue .AppImage Linux

### ISSUE THREAD

**Issue by SantosJMM** [kaiserdj/Darkorbit-client#52]
(node:3439) UnhandledPromiseRejectionWarning: Error: ERR_NAME_NOT_RESOLVED (-105) loading 'https://es4.darkorbit.com/indexInternal.es?action=internalDock&tpl=internalDockEquipment'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.failListener (electron/js2c/browser_init.js:205:1706)
    at Object.emit (events.js:315:20)
(node:3439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My PC

 OS: Linux Mint 20.3 x86_64
 Host: 20HD004AUS ThinkPad T470
Kernel: 5.4.0-97-generic
Uptime: 9 hours, 17 mins
Packages: 2852 (dpkg), 21 (flatpak)
Shell: bash 5.0.17
Resolution: 1366x768, 1920x1080
DE: Cinnamon
WM: Mutter (Muffin)
WM Theme: CBlack (CBlack)
Theme: CBlack [GTK2/3]
Icons: Mint-Y-Dark-Grey [GTK2/3]
CPU: Intel i5-7300U (4) @ 3.500GHz
GPU: Intel HD Graphics 620
Memory: 6841MiB / 15884MiB

**Comment by kaiserdj** [comment]
when did it happen to you?

**Comment by SantosJMM** [comment]
about 30 minutes ago

**Comment by kaiserdj** [comment]
I mean what did you do to cause that error?

**Comment by SantosJMM** [comment]
Between making some modifications in my ship configuration, at that moment I had the game client in base and I noticed that the ship configurator was crashing a lot and I opened the log and saw that error. For a moment I thought it was a problem with my machine but when I saw the error I realized that it was something related to a request from Bigpoint

**Comment by kaiserdj** [comment]
Being bigpoint issues, they are not client related.
I close the issue
