### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by alexperez52** [kaiserdj/Darkorbit-client#58]
### Incompatibility with macOS M1 (ARM64)
While trying to load the start client, I get an error message on the client window saying. `Couldn't load plugin`.
Terminal shows the following message:
`/Desktop/Darkorbit-client/flash/PepperFlashPlayer.plugin/Contents/MacOS/PepperFlashPlayer' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/local/lib/PepperFlashPlayer' (no such file), '/usr/lib/PepperFlashPlayer' (no such file)`

**Comment by kaiserdj** [comment]
Try this:

- Right-click the client executable icon and choose "Get Info" from the menu.
- Check "Open Using Rosetta".
- Close and relaunch.

Example of what should come out (I don't have a mac so I can't test it)
![image](https://user-images.githubusercontent.com/5487950/172656495-64c7e186-7304-4491-ba6a-5cc4a83dfcef.png)

**Comment by alexperez52** [comment]
There is no option to open using rosetta
<img width="262" alt="Screen Shot 2022-06-16 at 9 16 51 PM" src="https://user-images.githubusercontent.com/50466397/174223820-0f134f31-7738-4eee-b721-f731fa4c56e6.png">
