### ISSUE TITLE
small visual bug on ubuntu

### ISSUE THREAD

**Issue by bogdandudu** [kaiserdj/Darkorbit-client#59]
It's not a big issue, but it is annoying. Look on the right buttons, "galaxy gates ", auction ... 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
![Screenshot from 2022-06-13 09-03-38](https://user-images.githubusercontent.com/20356046/173290347-1d6b3057-de90-4606-98f0-2d54a18444bc.png)

**Comment by kaiserdj** [comment]
It's a very strange bug, try clearing the cache

**Comment by kaiserdj** [comment]
The issue is closed due to lack of information. If you wish to provide more information or any other type of comment, do not hesitate to reopen the issue.

**Comment by bogdandudu** [comment]
i did cleared the cache many times, no changes

**Comment by kaiserdj** [comment]
es

**Comment by bogdandudu** [comment]
i think so i updated every time it asked for update

**Comment by kaiserdj** [comment]
I will try to investigate about it, when I have some free time I will try to recreate the problem

**Comment by bogdandudu** [comment]
ok, thank you
