### ISSUE TITLE
copy sid not working 

### ISSUE THREAD

**Issue by bogdandudu** [kaiserdj/Darkorbit-client#68]
ubuntu 20.04 ...
no popup to copy seed but it still copy 
''
![Screenshot from 2022-12-08 09-32-24](https://user-images.githubusercontent.com/20356046/206386167-f5853788-f68e-4f82-9af9-560dc25e441d.png)

**Comment by ODAKAB** [comment]
same issue here, probably something in page changed after nova update

**Comment by bogdandudu** [comment]
if i can help, i can do tests ...

**Comment by ODAKAB** [comment]
> if i can help, i can do tests ...

You can compile and use this one if you know how to: https://github.com/kaiserdj/Darkorbit-client/pull/69

**Comment by bogdandudu** [comment]
> > if i can help, i can do tests ...
> 
> You can compile and use this one if you know how to: #69

thank you, i got some vulnerability report

**Comment by bogdandudu** [comment]
hi, can you please check when you have time, seems it doesn't detect sid anymore ... probably because DO updates,
Thanks

**Comment by bogdandudu** [comment]
i made a pull request for a fix to get sid from cookie instead of url:
https://github.com/kaiserdj/Darkorbit-client/pull/83/commits/3852e005e7a7b0bc58140f59d8af7a701d1de704

**Comment by kaiserdj** [comment]
PR accepted, thank you very much for the work and the help. I have added you to the Contributors list
