### ISSUE TITLE
HTTP 404 when sending resources via Skylab

### ISSUE THREAD

**Issue by GavBurke** [kaiserdj/Darkorbit-client#97]
Per description, using the Skylab gives a HTTP 404 within the client when trying to send resources over to the ship

Using 2.8.0 of client on Windows 11

**Comment by Cohvir** [comment]
Note: This happens on the official DarkOrbit client too.

Won't happen using any normal browser.

**Comment by paulposition97** [comment]
how can i solve this issue? tried from safari and chrome and still not working(from mac)

**Comment by GavBurke** [comment]
Given the comment about the official DO client doing this too, I would say it's an issue on Bigpoints end - maybe they've specifically disabled the Skylab.  A bug submission to Bigpoint would be needed.
